// Ejemplos ilustrativos procedentes de las fixtures de Laboratorio.test.tsx.
// No se leen investigaciones ni resultados del servidor.
import type { Laboratorio as Datos } from '../src/lib/laboratorio';

const DIANA: Datos['dianas'][number] = {
  uniprot: 'P10636',
  simbolo: 'MAPT',
  nombre: 'microtubule associated protein tau',
  hgnc: 'HGNC:6893',
  tambienLlamada: 'tau',
  hechos: 405,
  sabidos: 322,
  abiertos: 83,
  fuentes: 94,
  loQueSeSabe: [
    {
      tema: 'Orden temporal',
      enunciado: 'El p-tau181 en plasma se separa de los controles antes que el NfL.',
      referencia: 'Xie et al., 2026',
      fragmento: 'plasma p-tau181 diverged from stable controls earliest',
      investigacion: 'GFAP y NfL en portadores de APOE4',
    },
  ],
  causal: {
    aguasArriba: [{ otro: 'amiloide', tipo: 'base_curada', contexto: 'La patología amiloide precede a la propagación de tau' }],
    aguasAbajo: [{ otro: 'neurodegeneracion', tipo: 'base_curada', contexto: 'La tau patológica se asocia a la pérdida neuronal' }],
  },
  investigaciones: [
    { id: 'inv-1', titulo: 'Reducir amiloide y tau', hechos: 216 },
    { id: 'inv-1', titulo: 'Qué distingue a un biomarcador', hechos: 162 },
  ],
  deDonde: 'ambas',
  quimica: [
    // Un compuesto que PubChem sí tiene, con su fórmula, dentro de la diana.
    { nombre: 'donepezilo', juntas: 12, ontologiaId: 'CHEBI:53289', enPubchem: true, cid: 3152, formula: 'C24H29NO3', peso: '379.5', smiles: 'COC1=CC=C2C(=O)C(CC3CCN(CC3)CC4=CC=CC=C4)CC2=C1', inchikey: 'ADEBPBSSDYVVLD-UHFFFAOYSA-N', cerebro: { veredicto: 'compatible', motivo: 'peso 380, logP 4,2 y superficie polar 38,8 Å² están en la banda' }, url2d: null },
  ],
  deBanco: true,
  direccion: { pide: 'bajar', cuenta: { disminuye: 1 }, asoEncaja: true, motivo: '1 hipótesis pide bajarla' },
  // El oligonucleótido que ROSA2018 diseñaría: lo único que diseña de verdad.
  aso: {
    transcrito: 'ENST00000262410',
    esCanonico: true,
    maneSelect: null,
    // MAPT no tiene MANE Select: no hay acuerdo sobre cuál es la versión
    // representativa de tau, que es justo la pregunta de las isoformas 4R/3R.
    mismaIsoformaQueLaProteina: null,
    inicioCds: 151,
    finCds: 2652,
    transcritosDelGen: 55,
    largo: 6815,
    build: 'GRCh38',
    quimica: {
      arquitectura: 'gapmer 5-10-5',
      alas: "2'-O-metoxietilo (2'-MOE)",
      hueco: 'ADN (2\'-desoxi), es lo que reconoce la RNasa H1',
      enlaces: 'fosforotioato en todos los enlaces',
      citosinas: '5-metilcitosina',
      porQue: 'Es la arquitectura de los tres gapmers aprobados',
    },
    queHace: {
      hace: 'corta la producción: destruye el ARN mensajero',
      noHace: 'no toca la proteína que ya está fabricada; esa se va con el recambio normal de la célula',
      matiz: 'los agregados no son un depósito muerto: crecen reclutando proteína soluble',
      evidencia: 'en la fase 1b del BIIB080 la señal de PET bajó por debajo del punto de partida',
      aviso: 'eran dieciséis personas en la dosis alta',
    },
    via: {
      via: 'intratecal (punción lumbar)',
      porQue: 'los oligonucleótidos antisentido NO cruzan la barrera hematoencefálica',
      precedente: 'es la vía del nusinersén y la del diranersen contra tau',
      limite: 'la distribución por difusión deja menos fármaco en las regiones profundas',
    },
    candidatos: [
      {
        secuencia: 'CTCTCCCACTCCCACTTCTT',
        partes: { ala5: 'CTCTC', hueco: 'CCACTCCCAC', ala3: 'TTCTT' },
        posicion: 3230,
        hasta: 3249,
        diana: 'AAGAAGTGGGAGTGGGAGAG',
        region: 'región 3\' no traducida',
        gc: 0.55,
        cpg: 0,
        g4: false,
        autocomplementariedad: 0,
        rachaMasLarga: 3,
        motivosBuenos: 6,
        motivosMalos: 0,
        puntuacionMotivos: 6,
        pasa: true,
        cribado: false,
        avisoCribado: 'Sin alinear contra el transcriptoma. Un oligo encaja también donde el texto es casi igual, y ahí la RNasa H1 corta igual: sin este cribado el candidato no se puede pedir.',
        criba: {
          cribado: false,
          veredicto: 'sin cribar' as const,
          propios: 0,
          fuera: [],
          genesFuera: 0,
          transcritosFuera: 0,
          mismoSitioOtroNombre: [],
          genesMismoSitio: 0,
          transcritosMismoSitio: 0,
          porQue: 'Todavía sin comparar contra el transcriptoma humano.',
        },
      },
    ],
    ventanas: 6796,
    pasanFiltros: 1964,
    cribados: 0,
  },
  asoSinComprobar: false,
  // Tau: el modelo que se dibuja es predicho, y el PDB tiene cientos medidas.
  estructura: { url: 'https://alphafold.ebi.ac.uk/files/AF-P10636-F1-model_v6.cif', fuente: 'AlphaFold DB', licencia: 'CC BY 4.0', clase: 'predicha', medidas: 308, entradasPDB: ['5O3L'], urlPDB: 'https://www.rcsb.org/search?x' },
  hipotesis: [
    {
      id: 'hip-1',
      investigacionId: 'inv-1',
      titulo: 'Reducir MAPT limita la amplificación local de tau',
      estado: 'propuesta',
      decisionKiller: 'suspender',
      certeza: 'muy_baja',
      intervencion: 'Supresión de MAPT en neuronas hipocampales',
      direccion: 'disminuye',
      etapa: 'Modelo celular con inclusiones de tau ya establecidas',
      prediccionFalsable: 'se amplifica menos',
      sistema: 'ipsc',
      refuta: 'que la amplificación no cambie',
      controles: 'vector vacío y rescate',
      nivelDesenlace: 'celular',
      estadoExperimento: 'propuesto',
      prerregistradoEn: null,
    },
  ],
  enHipotesis: 1,
  intervenciones: ['Supresión de MAPT en neuronas hipocampales'],
  hojaDePedido: {
    hipotesis: 'Reducir MAPT limita la amplificación local de tau',
    certeza: 'muy_baja',
    queSeHace: 'Supresión de MAPT en neuronas hipocampales',
    identificador: 'UniProt P10636',
    sistema: 'ipsc',
    controles: 'vector vacío y rescate',
    refuta: 'que la amplificación no cambie',
    otrosExperimentos: [],
    sinExperimento: false,
    deBanco: true,
    contradiceLaIntervencion: false,
    faltan: [],
  },
};

/** Una diana que la evidencia señala y ninguna hipótesis propone: el hueco del
 *  programa, que es información y tiene que verse. */
const SIN_EXPERIMENTO: Datos['dianas'][number] = {
  ...DIANA,
  uniprot: 'P14136',
  simbolo: 'GFAP',
  nombre: 'glial fibrillary acidic protein',
  hgnc: 'HGNC:4235',
  tambienLlamada: '',
  hechos: 96,
  sabidos: 75,
  abiertos: 21,
  fuentes: 31,
  loQueSeSabe: [],
  investigaciones: [{ id: 'inv-1', titulo: 'Reducir amiloide y tau', hechos: 96 }],
  deDonde: 'evidencia',
  quimica: [],
  deBanco: false,
  // Aquí un oligo iría al revés de lo que concluyó la investigación.
  direccion: { pide: 'subir', cuenta: { aumenta: 1 }, asoEncaja: false, motivo: '1 hipótesis pide SUBIRLA. Un oligonucleótido antisentido la bajaría' },
  aso: null,
  asoSinComprobar: false,
  estructura: { url: 'https://alphafold.ebi.ac.uk/files/AF-P14136-F1-model_v6.cif', fuente: 'AlphaFold DB', licencia: 'CC BY 4.0', clase: 'predicha', medidas: null, entradasPDB: [], urlPDB: 'https://www.rcsb.org/search?y' },
  hipotesis: [],
  enHipotesis: 0,
  intervenciones: [],
  hojaDePedido: {
    hipotesis: null, certeza: null, queSeHace: '', identificador: 'UniProt P14136', sistema: null,
    controles: '', refuta: '', otrosExperimentos: [], sinExperimento: true, deBanco: false,
    contradiceLaIntervencion: false, faltan: [],
  },
};

/** El contrato largo llega aparte, al abrir el experimento. */
export const CONTRATOS = [
  {
    ...DIANA.hipotesis[0]!,
    protocolo: '1. Diferenciar neuronas isogénicas de iPSC.\n2. Suprimir MAPT con dos guías independientes.\n3. Sembrar con lisado de cerebro humano y lavar.\n4. Medir la siembra a los 14 días.',
    ensayo: 'Bioensayo celular de siembra validado, con inmunodetección de tau insoluble.',
    quePrueba: 'Permite separar la amplificación local de la captación inicial.',
    lecturas: [
      { nombre: 'Actividad de siembra intracelular', tipo: 'mecanismo', queConfirma: 'Baja con la supresión y se recupera con el rescate.', queRefuta: 'No cambia con compromiso de diana confirmado.' },
    ],
    confirma: 'Reducción de la siembra con dos guías y rescate.',
    tamanoMuestral: 'Tres diferenciaciones independientes por brazo.',
    alternativa: 'Que baje la captación inicial en vez de la amplificación.',
    decisionQueCambia: 'Si no cambia, se abandona MAPT como diana de amplificación local.',
    costeEstimado: 'Ocho semanas, 12.000 a 18.000 euros.',
    puenteAlBeneficio: 'Haría falta demostrar que la bajada de siembra se traduce en función neuronal.',
  },
];

export const DATOS: Datos = {
  oligoQueMandaria: {
    simbolo: 'MAPT',
    uniprot: 'P10636',
    nombre: 'microtubule associated protein tau',
    tambienLlamada: 'tau',
    candidato: DIANA.aso!.candidatos[0]!,
    criba: DIANA.aso!.candidatos[0]!.criba,
    diseño: { ...DIANA.aso!, candidatos: undefined } as never,
    puntos: 12.8,
    porQue: [
      { criterio: 'afirmaciones que la sostienen', valor: '322 de 405', puntos: 5.02 },
      { criterio: 'lo más lejos que llegó en el Killer', valor: 'suspender', puntos: 1.0 },
    ],
    frenteA: [{ simbolo: 'GFAP', uniprot: 'P14136', puntos: 11.2, porQueNo: 'suma 11.2 frente a 12.8; donde más pierde es en fuentes distintas' }],
    fueraDeConcurso: { subir: ['APP'], ninguna: ['NEFL'] },
    queLaCambiaria: 'Que aparezca evidencia de que bajar MAPT hace daño: la dirección es una puerta y no un término.',
  },
  dianas: [DIANA, SIN_EXPERIMENTO],
  compuestos: [
    {
      nombre: 'donepezilo',
      menciones: 12,
      sostenidos: 9,
      ontologiaId: 'CHEBI:53289',
      ontologia: 'CHEBI',
      enPubchem: true,
      cid: 3152,
      formula: 'C24H29NO3',
      peso: '379.5',
      iupac: '2-[(1-benzylpiperidin-4-yl)methyl]-5,6-dimethoxy-2,3-dihydro-1H-inden-1-one',
      smiles: 'COC1=C(C=C2CC(CC3CCN(CC3)CC4=CC=CC=C4)C(=O)C2=C1)OC',
      inchikey: 'ADEBPBSSDYVVLD-UHFFFAOYSA-N',
      logp: 4.2,
      tpsa: 38.8,
      cerebro: { veredicto: 'compatible', motivo: 'peso 380, logP 4,2 y superficie polar 38,8 Å² están en la banda' },
      url2d: null,
      url3d: null,
    },
    // Un anticuerpo: lo nombran 115 afirmaciones y PubChem no lo tiene como
    // molécula pequeña. Entra igual, y se dice por qué no hay SMILES.
    {
      nombre: 'lecanemab',
      menciones: 115,
      sostenidos: 88,
      ontologiaId: 'CHEBI:229272',
      ontologia: 'CHEBI',
      enPubchem: false,
      motivo: 'PubChem no tiene ningún compuesto con ese nombre',
      cid: null,
      formula: null,
      peso: null,
      iupac: null,
      smiles: null,
      inchikey: null,
      logp: null,
      tpsa: null,
      cerebro: { veredicto: 'no_comprobable', motivo: 'faltan propiedades para juzgarlo' },
      url2d: null,
      url3d: null,
    },
  ],
  nombradasSinEstructura: [{ simbolo: 'TREM2', hechos: 18, sabidos: 14, motivo: 'resuelta en HGNC pero sin acceso de UniProt' }],
  descartadasPorAlias: [{ simbolo: 'AGPS', hechos: 11, sabidos: 8, motivo: 'el nombre que la trajo era un alias' }],
  sinResolver: [],
  resumen: {
    dianas: 2,
    compuestos: 2,
    hipotesisVivas: 34,
    hipotesisConDiana: 29,
    sinDiana: 5,
    afirmaciones: 501,
    sostenidas: 397,
    hechosDeLaInvestigacion: 1242,
    sinExperimento: 1,
    deBanco: 1,
    conAso: 1,
    asoAlReves: 1,
    investigaciones: 6,
  },
};
